sonar.projectKey=riwi-sportsline
sonar.projectName=Riwi SportsLine
sonar.projectVersion=1.0

# Código fuente
sonar.sources=src

# Tests
sonar.tests=test
sonar.test.inclusions=**/*.spec.ts

# Reporte de cobertura generado por Jest
sonar.typescript.lcov.reportPaths=coverage/lcov.info

# Lenguaje
sonar.language=ts
sonar.sourceEncoding=UTF-8